version: '3.1'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=imobleads
    volumes:
      - ~/app/gobarber/src/database:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=docker
